cascade_pid_controller:
  ros__parameters:
    control_hz: 100.0
    tau_scale: 0.35
    autostart: false
    gravity_scale:
    - 1.0
    - 1.0
    - 1.0
    cascade_hold: true
    position_kp:
    - 20.0
    - 24.5
    - 7.0
    position_ki:
    - 2.0
    - 1.5
    - 4.0
    position_kd:
    - 0.8
    - 0.7
    - 1.0
    position_integral_limit:
    - 0.3
    - 0.3
    - 0.3
    max_transition_error_rad: 0.1
    max_track_error_rad: 0.1
    state_timeout: 0.25
    joint_margin_rad: 0.05
    command_heartbeat_nm: 1.0e-06
